import Head from "next/head";
import React from "react";

const Meta = () => {
    return (
        <Head>
            <title>Yariga</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <meta name="keyword" content="real estate, property, dashboard" />
            <link rel="icon" href="./Favicon.svg" />
        </Head>
    );
};

export default Meta;
